# Numpy

- NumPy is a general-purpose array-processing package.
- Numpy was created to work with multidmensional arrays.
- It is the fundamental package for scientific computing with Python.
- It is open-source library.

# Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

- Arrays are very frequently used in data science, where speed and resources are very important.

In [1]:
#Importing necessary library

In [4]:
import numpy as np

In [6]:
#Array Creation
a = np.array([1,2,3,4,5,6,7,8,9])

In [7]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a.ndim

1

In [9]:
z = np.array(10)
z.ndim

0

In [4]:
#Two dimensional array

In [10]:
two = np.array([[1,2,3]])
two.ndim

2

In [5]:
#Three dimensional array

In [11]:
three = np.array([[[1,2,3]]])
three.ndim

3

In [6]:
#Change the data type of the array elements.

In [12]:
z = np.array([10,'Python',10.2, True])

In [13]:
z

array(['10', 'Python', '10.2', 'True'], dtype='<U32')

In [15]:
x = np.array([10,20,30], dtype = 'float')
x

array([10., 20., 30.])

# Other ways of creating an array
1. arange
2. linspace
3. zeros
4. ones
5. random

In [16]:
z = np.arange(1,50)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
a = np.linspace(10,20,50, retstep=True)
a

(array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
        11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
        12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
        13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
        14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
        15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
        16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
        17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
        18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
        19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ]),
 0.20408163265306123)

In [22]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones([5,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
#Numpy Random functions

In [25]:
np.random.rand(5,6)

array([[0.84114869, 0.60078585, 0.15692279, 0.32515826, 0.30975952,
        0.25992294],
       [0.90253771, 0.91484393, 0.30442676, 0.46974757, 0.06146917,
        0.41349354],
       [0.08355923, 0.92835805, 0.63518451, 0.20043051, 0.21597791,
        0.33299787],
       [0.16488609, 0.89507606, 0.50370963, 0.37833804, 0.26945916,
        0.54088111],
       [0.63022628, 0.11094457, 0.39559758, 0.86954399, 0.86142924,
        0.5236373 ]])

In [26]:
np.random.randn(2,4)

array([[-1.15257297,  0.6714114 , -0.33965224,  1.91666807],
       [ 1.2269504 , -0.48304355, -1.14914584,  0.03057618]])

In [28]:
np.random.random_sample(200)

array([0.42247057, 0.72995596, 0.11484021, 0.79210461, 0.95327129,
       0.49267518, 0.5508207 , 0.82180079, 0.1326942 , 0.5751732 ,
       0.02202702, 0.67676256, 0.25291906, 0.92680767, 0.82511803,
       0.75171303, 0.30107281, 0.08070868, 0.47885197, 0.16306246,
       0.05110094, 0.99782861, 0.78259631, 0.77655395, 0.57386182,
       0.37663595, 0.7646808 , 0.13543488, 0.04000237, 0.27634119,
       0.78911928, 0.44280034, 0.73565186, 0.09760526, 0.30481221,
       0.46331416, 0.59671539, 0.33476889, 0.6317446 , 0.85518951,
       0.57739233, 0.7877702 , 0.31415924, 0.96814334, 0.82081978,
       0.0424899 , 0.93697096, 0.6120419 , 0.23989714, 0.62845719,
       0.78777759, 0.11854518, 0.08524446, 0.483329  , 0.13270441,
       0.79044786, 0.47262328, 0.50731137, 0.15013999, 0.53158695,
       0.89248197, 0.82536166, 0.13112588, 0.58458713, 0.35499703,
       0.5443966 , 0.26236081, 0.90203554, 0.62998646, 0.96835242,
       0.80792966, 0.70300853, 0.77295992, 0.96154194, 0.40720

# Slicing and Indexing of arrays

In [29]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [30]:
a[2]

3

In [31]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a[1,1]

5

In [34]:
a[:,0:2]

array([[1, 2],
       [4, 5]])

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a[[0,1],[0,2]]

array([1, 6])

In [39]:
a[[0,1],[2,0]]

array([3, 4])

In [40]:
a[:,1]

array([2, 5])

# Reshaping the arrays 

In [43]:
x = np.random.randn(4,2)
x

array([[ 1.42114514,  0.00498214],
       [-0.70548094, -0.63805902],
       [-0.60230537, -0.06135805],
       [-0.01032856,  0.34217645]])

In [44]:
x.reshape(8,1)

array([[ 1.42114514],
       [ 0.00498214],
       [-0.70548094],
       [-0.63805902],
       [-0.60230537],
       [-0.06135805],
       [-0.01032856],
       [ 0.34217645]])

In [45]:
x.reshape(1,8)

array([[ 1.42114514,  0.00498214, -0.70548094, -0.63805902, -0.60230537,
        -0.06135805, -0.01032856,  0.34217645]])

In [46]:
x.reshape(4,3)

ValueError: cannot reshape array of size 8 into shape (4,3)

In [47]:
x.reshape(2,-1)

array([[ 1.42114514,  0.00498214, -0.70548094, -0.63805902],
       [-0.60230537, -0.06135805, -0.01032856,  0.34217645]])

In [48]:
x.reshape(-1,4)

array([[ 1.42114514,  0.00498214, -0.70548094, -0.63805902],
       [-0.60230537, -0.06135805, -0.01032856,  0.34217645]])

In [49]:
x.reshape(-1,-1)

ValueError: can only specify one unknown dimension

# Aggregate Functions

- The Python numpy aggregate functions are sum, min, max, mean, average, product, median, standard deviation, variance,  percentile, and corrcoef.

In [50]:
x

array([[ 1.42114514,  0.00498214],
       [-0.70548094, -0.63805902],
       [-0.60230537, -0.06135805],
       [-0.01032856,  0.34217645]])

In [51]:
x.mean()

-0.031153526350581162

In [53]:
x.min()

-0.7054809438724947

In [54]:
x.max()

1.4211451397417818